name: Daily Activity Post - githubX

on:
  schedule:
    # Runs every day at 7:00 AM ICT (00:00 UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Keep manual trigger

jobs:
  build_and_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Simple Test Step # Remove this test step
      #   run: echo "Simplified daily_report.yml is visible! Dependencies step restored."
      - name: Run update script # Restore original step
        env:
          # Map ALL secrets defined as *_env_var in config.yaml here
          # These names MUST match the secret names created in GitHub repo settings
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          USER_GITHUB_PAT: ${{ secrets.USER_GITHUB_PAT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          # Add Garmin secrets
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          # Add other secrets here if you enable more sources/targets
          # DRY_RUN: "false" # Optional: set to "true" in secrets for testing
        run: python main.py
