name: Daily Activity Post - githubX

on:
  # schedule: # Temporarily removed
  #   - cron: "0 7 * * *"
  workflow_dispatch: # Keep manual trigger

jobs:
  build_and_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # - name: Install dependencies # Temporarily removed
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Simple Test Step # Replaced original run step
        run: echo "Simplified daily_report.yml is visible!"
      # - name: Run update script # Temporarily removed original step
      #   env:
      #     GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      #     USER_GITHUB_PAT: ${{ secrets.USER_GITHUB_PAT }}
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      #     X_API_KEY: ${{ secrets.X_API_KEY }}
      #     X_API_SECRET: ${{ secrets.X_API_SECRET }}
      #     X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      #     X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
      #   run: python main.py
